text\:\:book = book
text\:\:book-part = book-chapter
text\:\:conference-speech = conference-paper
text\:\:journal-article = journal-article
text\:\:patent = patent
text\:\:report = report
text\:\:thesis = dissertation-thesis
text\:\:working-paper = working-paper