# Mapping between work type supported by ORCID and the DSpace common publication's types
# website = Controlled Vocabulary for Resource Type Genres::interactive resource::website
# data-set = Controlled Vocabulary for Resource Type Genres::dataset
book = text::book
# Legacy version of book
edited-book	= text::book
book-chapter = text::book-part
conference-paper = text::conference-speech
conference-output = text::conference-speech
# Legacy version of conference-output
conference-abstract	= text::conference-speech
conference-presentation = text::conference-speech
conference-poster = text::conference-speech
conference-proceedings = text::conference-speech
journal-article = text::journal-article
newspaper-article = text::journal-article
magazine-article = text::journal-article
preprint = text::journal-article
journal-issue = text::journal-article
review = text::journal-article
patent = text::patent
report = text::report
# book-review = Controlled Vocabulary for Resource Type Genres::text::review::book review
dissertation-thesis = text::thesis
working-paper = text::working-paper