text\:\:book = BOOK
text\:\:book-part = CHAP
text\:\:conference-speech = CONF
text\:\:journal-article = JOUR
text\:\:report = RPRT
text\:\:working-paper = UNPB
text\:\:patent = PAT
text\:\:thesis = THES