# Mapping for crossref types.
monograph = text::book
book-chapter = text::book-part
journal-article = text::journal-article
proceedings-article = text::conference-speech
posted-content = text::conference-speech
report = text::report