
text\:\:book = book
text\:\:book-part = chapter
text\:\:journal-article = article-journal
text\:\:conference-speech = paper-conference
text\:\:patent = patent
text\:\:report = report
text\:\:thesis = thesis
text\:\:working-paper = article-journal